export const wordData = {
    "verbs": [
        {"kanji":"食<rt>た<\/rt>べる","type":"ru","eng":"eat"},
        {"kanji":"飲<rt>の<\/rt>む","type":"u","eng":"drink"},
        {"kanji":"見<rt>み<\/rt>る","type":"ru","eng":"see, look"},
        {"kanji":"聞<rt>き<\/rt>く","type":"u","eng":"hear, listen"},
        {"kanji":"読<rt>よ<\/rt>む","type":"u","eng":"read"},
        {"kanji":"買<rt>か<\/rt>う","type":"u","eng":"buy"},
        {"kanji":"する","type":"irv","eng":"do, make"},
        {"kanji":"起<rt>お<\/rt>きる","type":"ru","eng":"get up, wake up"},
        {"kanji":"寝<rt>ね<\/rt>る","type":"ru","eng":"sleep, go to bed"},
        {"kanji":"行<rt>い<\/rt>く","type":"irv","eng":"go"},
        {"kanji":"来<rt>く<\/rt>る","type":"irv","eng":"come"},
        {"kanji":"帰<rt>かえ<\/rt>る","type":"u","eng":"return, go home"},
        {"kanji":"書<rt>か<\/rt>く","type":"u","eng":"write"},
        {"kanji":"泳<rt>およ<\/rt>ぐ","type":"u","eng":"swim"},
        {"kanji":"ある","type":"irv","eng":"have, exists, is (inanimate)"},
        {"kanji":"いる","type":"ru","eng":"exists, is (living things)"},
        {"kanji":"取<rt>と<\/rt>る","type":"u","eng":"take, steal"},
        {"kanji":"働<rt>はたら<\/rt>く","type":"u","eng":"work"},
        {"kanji":"会<rt>あ<\/rt>う","type":"u","eng":"meet"},
        {"kanji":"贈<rt>おく<\/rt>る","type":"u","eng":"send, give a present"},
        {"kanji":"掛<rt>か<\/rt>ける","type":"ru","eng":"hang, sit, call"},
        {"kanji":"あげる","type":"ru","eng":"give"},
        {"kanji":"もらう","type":"u","eng":"receive"},
        {"kanji":"聞<rt>き<\/rt>く","type":"u","eng":"hear, listen"},
        {"kanji":"終<rt>お<\/rt>わる","type":"u","eng":"end"},
        {"kanji":"休<rt>やす<\/rt>む","type":"u","eng":"rest, be absent"},
        {"kanji":"登<rt>のぼ<\/rt>る","type":"u","eng":"climb, go up"},
        {"kanji":"習<rt>なら<\/rt>う","type":"u","eng":"learn"},
        {"kanji":"分<rt>わ<\/rt>かる","type":"u","eng":"understand"},
        {"kanji":"思<rt>おも<\/rt>う","type":"u","eng":"think, believe"},
        {"kanji":"付<rt>つ<\/rt>ける","type":"ru","eng":"attach, apply"},
        {"kanji":"急<rt>いそ<\/rt>ぐ","type":"u","eng":"hurry"},
        {"kanji":"走<rt>はし<\/rt>る","type":"u","eng":"run"},
        {"kanji":"疲<rt>つか<\/rt>れる","type":"ru","eng":"get tired"},
        {"kanji":"使<rt>つか<\/rt>う","type":"u","eng":"use"},
        {"kanji":"いらっしゃる","type":"u","eng":"come, go, be (honorific)"},
        {"kanji":"申<rt>もう<\/rt>す","type":"u","eng":"say (humble)"},
        {"kanji":"出<rt>で<\/rt>かける","type":"ru","eng":"go out"},
        {"kanji":"待<rt>ま<\/rt>つ","type":"u","eng":"wait"},
        {"kanji":"伝<rt>つた<\/rt>える","type":"ru","eng":"convey, transmit"},
        {"kanji":"話<rt>はな<\/rt>す","type":"u","eng":"talk, speak"},
        {"kanji":"呼<rt>よ<\/rt>ぶ","type":"u","eng":"call, invite"},
        {"kanji":"教<rt>おし<\/rt>える","type":"ru","eng":"teach, tell"},
        {"kanji":"貸<rt>か<\/rt>す","type":"u","eng":"lend, loan"},
        {"kanji":"開<rt>あ<\/rt>ける","type":"ru","eng":"open"},
        {"kanji":"手<rt>て<\/rt>伝<rt>つだ<\/rt>う","type":"u","eng":"help"},
        {"kanji":"閉<rt>し<\/rt>める","type":"ru","eng":"close"},
        {"kanji":"言<rt>い<\/rt>う","type":"u","eng":"say, utter"},
        {"kanji":"曲<rt>ま<\/rt>がる","type":"u","eng":"turn, bend"},
        {"kanji":"返<rt>かえ<\/rt>す","type":"u","eng":"return (something), put back"},
        {"kanji":"上<rt>あ<\/rt>がる","type":"u","eng":"go up, rise"},
        {"kanji":"座<rt>すわ<\/rt>る","type":"u","eng":"sit"},
        {"kanji":"召<rt>め<\/rt>し<rt>し<\/rt>上<rt>あ<\/rt>がる","type":"u","eng":"eat, drink (honorific)"},
        {"kanji":"洗<rt>あら<\/rt>う","type":"u","eng":"wash"},
        {"kanji":"浴<rt>あ<\/rt>びる","type":"ru","eng":"bathe, shower"},
        {"kanji":"押<rt>お<\/rt>す","type":"u","eng":"push, press"},
        {"kanji":"決<rt>き<\/rt>める","type":"ru","eng":"decide, choose"},
        {"kanji":"集<rt>あつ<\/rt>める","type":"ru","eng":"gather, collect"},
        {"kanji":"乗<rt>の<\/rt>る","type":"u","eng":"board, ride"},
        {"kanji":"作<rt>つく<\/rt>る","type":"u","eng":"make, build"},
        {"kanji":"掛<rt>か<\/rt>かる","type":"u","eng":"take (time, money)"},
        {"kanji":"降<rt>お<\/rt>りる","type":"ru","eng":"get off, go down"},
        {"kanji":"乗<rt>の<\/rt>り換<rt>か<\/rt>える","type":"ru","eng":"transfer, change (trains)"},
        {"kanji":"答<rt>こた<\/rt>える","type":"ru","eng":"answer, reply"},
        {"kanji":"入<rt>はい<\/rt>る","type":"u","eng":"enter"},
        {"kanji":"持<rt>も<\/rt>つ","type":"u","eng":"hold, have"},
        {"kanji":"知<rt>し<\/rt>る","type":"u","eng":"know"},
        {"kanji":"住<rt>す<\/rt>む","type":"u","eng":"live, inhabit"},
        {"kanji":"通<rt>かよ<\/rt>う","type":"u","eng":"commute, attend"},
        {"kanji":"止<rt>と<\/rt>める","type":"ru","eng":"stop, park"}
    ],
    "adjectives": [
        {"kanji":"いい","type":"ira","eng":"good"},
        {"kanji":"かっこいい","type":"ira","eng":"cool, handsome"},
        {"kanji":"赤<rt>あか<\/rt>い","type":"i","eng":"red"},
        {"kanji":"新<rt>あたら<\/rt>しい","type":"i","eng":"new"},
        {"kanji":"暑<rt>あつ<\/rt>い","type":"i","eng":"hot (weather)"},
        {"kanji":"危<rt>あぶ<\/rt>ない","type":"i","eng":"dangerous"},
        {"kanji":"美<rt>お<\/rt>味<rt>い<\/rt>しい","type":"i","eng":"delicious"},
        {"kanji":"大<rt>おお<\/rt>きい","type":"i","eng":"big"},
        {"kanji":"遅<rt>おそ<\/rt>い","type":"i","eng":"late, slow"},
        {"kanji":"面<rt>おも<\/rt>白<rt>しろ<\/rt>い","type":"i","eng":"interesting, funny"},
        {"kanji":"可<rt>か<\/rt>愛<rt>い<\/rt>い","type":"i","eng":"cute, pretty"},
        {"kanji":"辛<rt>から<\/rt>い","type":"i","eng":"spicy"},
        {"kanji":"小<rt>ちい<\/rt>さい","type":"i","eng":"small"},
        {"kanji":"近<rt>ちか<\/rt>い","type":"i","eng":"close, near"},
        {"kanji":"詰<rt>つ<\/rt>まらない","type":"i","eng":"boring"},
        {"kanji":"強<rt>つよ<\/rt>い","type":"i","eng":"strong"},
        {"kanji":"遠<rt>とお<\/rt>い","type":"i","eng":"far"},
        {"kanji":"長<rt>なが<\/rt>い","type":"i","eng":"long"},
        {"kanji":"早<rt>はや<\/rt>い","type":"i","eng":"early, fast"},
        {"kanji":"低<rt>ひく<\/rt>い","type":"i","eng":"low, short"},
        {"kanji":"古<rt>ふる<\/rt>い","type":"i","eng":"old"},
        {"kanji":"難<rt>むずか<\/rt>しい","type":"i","eng":"difficult"},
        {"kanji":"優<rt>やさ<\/rt>しい","type":"i","eng":"kind, gentle"},
        {"kanji":"安<rt>やす<\/rt>い","type":"i","eng":"cheap, inexpensive"},
        {"kanji":"悪<rt>わる<\/rt>い","type":"i","eng":"bad"},
        {"kanji":"静<rt>しず<\/rt>か","type":"na","eng":"quiet"},
        {"kanji":"元<rt>げん<\/rt>気<rt>き<\/rt>","type":"na","eng":"healthy, energetic"},
        {"kanji":"親<rt>しん<\/rt>切<rt>せつ<\/rt>","type":"na","eng":"kind"},
        {"kanji":"大<rt>たい<\/rt>変<rt>へん<\/rt>","type":"na","eng":"hard, tough"},
        {"kanji":"有<rt>ゆう<\/rt>名<rt>めい<\/rt>","type":"na","eng":"famous"},
        {"kanji":"好<rt>す<\/rt>き","type":"na","eng":"like, love"},
        {"kanji":"嫌<rt>きら<\/rt>い","type":"na","eng":"dislike, hate"},
        {"kanji":"便利<rt>べんり<\/rt>","type":"na","eng":"convenient"},
        {"kanji":"素敵<rt>すてき<\/rt>","type":"na","eng":"lovely, nice"},
        {"kanji":"大<rt>じゅう<\/rt>切<rt>たい<\/rt>","type":"na","eng":"important, precious"}
    ]
};
